# Generated by Django 6.0.3 on 2026-04-02 19:52

import appAcervo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição/História')),
                ('categoria', models.CharField(choices=[('REL', 'Religiosidade'), ('ARQ', 'Arquitetura e Urbanismo'), ('CUL', 'Cultura e Eventos'), ('PES', 'Personalidades'), ('PAI', 'Paisagens Naturais'), ('COT', 'Cotidiano'), ('MON', 'Monumentos')], max_length=3, verbose_name='Categoria')),
                ('data_estimada', models.DateField(blank=True, null=True, verbose_name='Data da foto (Estimada)')),
                ('credito', models.CharField(help_text='Nome da pessoa ou orgão que disponibilizou a imagem.', max_length=150, verbose_name='Cedido por / Fonte')),
                ('imagem', models.ImageField(max_length=500, upload_to=appAcervo.models.renomear_arquivo, verbose_name='Arquivo da foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
