# Generated by Django 6.0.4 on 2026-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('REL', 'Religiosidade'), ('ARQ', 'Arquitetura e Urbanismo'), ('CUL', 'Cultura e Eventos'), ('PES', 'Personalidades'), ('PAI', 'Paisagens Naturais'), ('COT', 'Cotidiano'), ('SIM', 'Símbolos'), ('MON', 'Monumentos')], max_length=3, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='data_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fundação (Estimada)'),
        ),
    ]
